const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  price: { type: Number, required: true },
  originalPrice: { type: Number },
  imageUrl: { type: String, required: true },
  category: { type: String, required: true }, // Should match a Category name
  rating: { type: Number, min: 0, max: 5 },
  stock: { type: Number, required: true, default: 0 },
  tags: [{ type: String }], // e.g., "New", "Sale", "Popular", "Order Again", "20% OFF"
}, {
  toJSON: { virtuals: true },
  toObject: { virtuals: true },
  timestamps: true,
});

productSchema.virtual('id').get(function() {
  return this._id.toHexString();
});

// For search functionality (optional, but good for the search endpoint)
productSchema.index({ name: 'text', description: 'text', category: 'text', tags: 'text' });

const Product = mongoose.model('Product', productSchema);

const mockProducts = [
  // Fruits & Vegetables
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Fresh Apples (Fuji)',
    description: 'Crisp and sweet Fuji apples, perfect for snacking or baking. Pack of 6.',
    price: 350,
    originalPrice: 400,
    imageUrl: 'https://placehold.co/300x300/FF6347/FFFFFF?text=Apples',
    category: 'Fruits & Vegetables',
    rating: 4.5,
    stock: 100,
    tags: ['Popular', 'Sale', 'Healthy', 'Fruits'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Organic Spinach',
    description: 'Freshly picked organic spinach, rich in vitamins. 250g pack.',
    price: 150,
    imageUrl: 'https://placehold.co/300x300/3CB371/FFFFFF?text=Spinach',
    category: 'Fruits & Vegetables',
    rating: 4.7,
    stock: 75,
    tags: ['Organic', 'Healthy', 'Vegetables', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Ripe Bananas',
    description: 'A bunch of sweet and ripe bananas, great for energy. Approx 1kg.',
    price: 120,
    imageUrl: 'https://placehold.co/300x300/FFD700/333333?text=Bananas',
    category: 'Fruits & Vegetables',
    rating: 4.3,
    stock: 120,
    tags: ['Popular', 'Fruits', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Carrots',
    description: 'Fresh and crunchy carrots, 500g pack.',
    price: 80,
    imageUrl: 'https://placehold.co/300x300/FFA500/FFFFFF?text=Carrots',
    category: 'Fruits & Vegetables',
    rating: 4.2,
    stock: 90,
    tags: ['Vegetables', 'Healthy'],
  },
   {
    _id: new mongoose.Types.ObjectId(),
    name: 'Local Mangoes (Seasonal)',
    description: 'Sweet and juicy local mangoes, taste of the season. Per Kg.',
    price: 250,
    originalPrice: 280,
    imageUrl: 'https://placehold.co/300x300/FF8C00/FFFFFF?text=Mangoes',
    category: 'Fruits & Vegetables',
    rating: 4.8,
    stock: 60,
    tags: ['Popular', 'Seasonal', 'Fruits', 'Sale'],
  },

  // Dairy & Eggs
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Fresh Milk (1 Litre)',
    description: 'Pasteurized full-cream dairy milk. 1 litre carton.',
    price: 210,
    imageUrl: 'https://placehold.co/300x300/87CEFA/FFFFFF?text=Milk',
    category: 'Dairy & Eggs',
    rating: 4.6,
    stock: 80,
    tags: ['Popular', 'Dairy', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Farm Fresh Eggs (Dozen)',
    description: 'A dozen large, farm-fresh brown eggs.',
    price: 300,
    originalPrice: 320,
    imageUrl: 'https://placehold.co/300x300/F5DEB3/333333?text=Eggs',
    category: 'Dairy & Eggs',
    rating: 4.7,
    stock: 60,
    tags: ['Sale', 'Eggs', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Natural Yogurt',
    description: 'Plain natural yogurt, great for breakfast or cooking. 500g tub.',
    price: 180,
    imageUrl: 'https://placehold.co/300x300/E0FFFF/333333?text=Yogurt',
    category: 'Dairy & Eggs',
    rating: 4.4,
    stock: 50,
    tags: ['Dairy', 'Healthy'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Cheddar Cheese Block',
    description: 'Rich and creamy cheddar cheese block. 200g.',
    price: 450,
    imageUrl: 'https://placehold.co/300x300/FFDA63/333333?text=Cheese',
    category: 'Dairy & Eggs',
    rating: 4.5,
    stock: 40,
    tags: ['Popular', 'Dairy', '10% OFF'],
  },

  // Bakery
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Whole Wheat Bread',
    description: 'Soft and healthy whole wheat bread loaf.',
    price: 150,
    imageUrl: 'https://placehold.co/300x300/D2B48C/FFFFFF?text=Bread',
    category: 'Bakery',
    rating: 4.3,
    stock: 70,
    tags: ['Bakery', 'Healthy', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Chocolate Croissants (Pack of 2)',
    description: 'Buttery and flaky croissants with a rich chocolate filling.',
    price: 250,
    imageUrl: 'https://placehold.co/300x300/8B4513/FFFFFF?text=Croissants',
    category: 'Bakery',
    rating: 4.6,
    stock: 40,
    tags: ['Popular', 'Bakery', 'Treats'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Plain Bagels (Pack of 4)',
    description: 'Classic plain bagels, perfect for toasting.',
    price: 200,
    imageUrl: 'https://placehold.co/300x300/F5F5DC/333333?text=Bagels',
    category: 'Bakery',
    rating: 4.2,
    stock: 50,
    tags: ['Bakery'],
  },

  // Meat & Seafood
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Chicken Breast (Boneless, Skinless)',
    description: 'Fresh, boneless, and skinless chicken breast. Approx 500g.',
    price: 750,
    imageUrl: 'https://placehold.co/300x300/FFE4E1/333333?text=Chicken',
    category: 'Meat & Seafood',
    rating: 4.7,
    stock: 30,
    tags: ['Popular', 'Meat', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Minced Beef (Lean)',
    description: 'Lean minced beef, perfect for various dishes. 500g pack.',
    price: 900,
    imageUrl: 'https://placehold.co/300x300/DC143C/FFFFFF?text=Beef',
    category: 'Meat & Seafood',
    rating: 4.5,
    stock: 25,
    tags: ['Meat', 'Sale', '15% OFF'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Fresh Salmon Fillet',
    description: 'Premium quality fresh salmon fillet. Approx 200g.',
    price: 1200,
    imageUrl: 'https://placehold.co/300x300/FA8072/FFFFFF?text=Salmon',
    category: 'Meat & Seafood',
    rating: 4.8,
    stock: 20,
    tags: ['Popular', 'Seafood', 'Healthy'],
  },

  // Snacks
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Potato Chips (Salted)',
    description: 'Classic salted potato chips, family size bag.',
    price: 180,
    imageUrl: 'https://placehold.co/300x300/FFD700/333333?text=Chips',
    category: 'Snacks',
    rating: 4.2,
    stock: 100,
    tags: ['Popular', 'Snacks', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Chocolate Chip Cookies',
    description: 'Deliciously soft chocolate chip cookies. Pack of 10.',
    price: 220,
    imageUrl: 'https://placehold.co/300x300/A0522D/FFFFFF?text=Cookies',
    category: 'Snacks',
    rating: 4.5,
    stock: 60,
    tags: ['Snacks', 'Treats', 'Sale'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Roasted Almonds',
    description: 'Healthy and crunchy roasted almonds. 150g pack.',
    price: 350,
    imageUrl: 'https://placehold.co/300x300/DEB887/333333?text=Almonds',
    category: 'Snacks',
    rating: 4.6,
    stock: 45,
    tags: ['Snacks', 'Healthy', 'Nuts'],
  },
   {
    _id: new mongoose.Types.ObjectId(),
    name: 'Popcorn (Microwave)',
    description: 'Butter flavored microwave popcorn. 3 pack.',
    price: 150,
    imageUrl: 'https://placehold.co/300x300/FFFACD/333333?text=Popcorn',
    category: 'Snacks',
    rating: 4.1,
    stock: 80,
    tags: ['Snacks', 'Order Again'],
  },

  // Beverages
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Orange Juice (1 Litre)',
    description: 'Freshly squeezed orange juice, no added sugar. 1 litre bottle.',
    price: 300,
    imageUrl: 'https://placehold.co/300x300/FF8C00/FFFFFF?text=Juice',
    category: 'Beverages',
    rating: 4.4,
    stock: 70,
    tags: ['Popular', 'Beverages', 'Order Again'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Cola (6 Pack)',
    description: 'Classic cola soda drink, 6 x 330ml cans.',
    price: 450,
    imageUrl: 'https://placehold.co/300x300/777777/FFFFFF?text=Cola',
    category: 'Beverages',
    rating: 4.2,
    stock: 90,
    tags: ['Beverages', 'Soda', 'Popular', 'Sale', '20% OFF'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Mineral Water (1.5 Litre)',
    description: 'Pure and refreshing mineral water. 1.5 litre bottle.',
    price: 80,
    imageUrl: 'https://placehold.co/300x300/ADD8E6/333333?text=Water',
    category: 'Beverages',
    rating: 4.7,
    stock: 150,
    tags: ['Beverages', 'Healthy', 'Order Again'],
  },

  // Household Essentials
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Dishwashing Liquid',
    description: 'Lemon scented dishwashing liquid. 500ml bottle.',
    price: 200,
    imageUrl: 'https://placehold.co/300x300/FFFF00/333333?text=Dish+Soap',
    category: 'Household Essentials',
    rating: 4.3,
    stock: 60,
    tags: ['Household', 'Cleaning'],
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Toilet Paper (4 Rolls)',
    description: 'Soft and absorbent toilet paper, 4-roll pack.',
    price: 350,
    imageUrl: 'https://placehold.co/300x300/E6E6FA/333333?text=ToiletPaper',
    category: 'Household Essentials',
    rating: 4.5,
    stock: 50,
    tags: ['Household', 'Essentials', 'Order Again'],
  },
];

module.exports = { Product, mockProducts };